version: '3.3'

services:

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.3.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME:-192.168.2.102}
      KAFKA_CREATE_TOPICS: "topicin:1:1,topicout:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mongo:
    image: mongo:4.2.0-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
    ports:
      - "27017:27017"

  mongo-ui:
    image: mongo-express:0.49
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-root}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-example}
    ports:
      - "8081:8081"

  maven-build:
    build:
      context: .
      dockerfile: Dockerfile.maven
      args:
        - MAVEN_USER_NAME=aronk
        - MAVEN_USER_ID=567
        - MAVEN_GROUP_ID=567
        - MAVEN_GROUP_NAME=aronk
    environment:
      MAVEN_CONFIG: /var/maven/.m2
      MAVEN_OPTS: -Xmx2048m
      APP_MONGODB_HOST: mongo
      APP_KAFKA_BROKER: kafka:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ~/.docker:/root/.docker
      - $HOME/.m2:/var/maven/.m2
      - ${PWD}:/usr/src/app
    working_dir: /usr/src/app
    user: aronk
    command: mvn -e -B -Duser.home=/var/maven clean verify -DargLine="-Xmx1536m"

  fs-app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_MONGODB_HOST: mongo
      APP_KAFKA_BROKER: kafka:9092
    ports:
      - "8080:8080"
